#!/bin/bash
# -ex

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Builds a Docker container image for running Azure Speech SDK batch jobs, built on the batchkit library.

# Work in the repo root directory.
REL_SCRIPT_DIR=$(dirname "$0")
SCRIPT_DIR=$(realpath "$REL_SCRIPT_DIR")
pushd "${SCRIPT_DIR}/../.."

echo cwd is 'pwd'
echo SCRIPT_DIR is $SCRIPT_DIR

rm -rf ./dist/batchkit_examples-* ./build/lib/batchkit_examples ./build/scripts-* batchkit_examples.egg-info
./setup_examples.py sdist bdist_wheel
BATCHKIT_EXAMPLES_PKG=$(python setup_examples.py --fullname | tr -d "\n")
docker build "$@" -f "${SCRIPT_DIR}/Dockerfile" . --build-arg BATCHKIT_EXAMPLES_PKG="${BATCHKIT_EXAMPLES_PKG}" -t speech-batch-kit:test

popd
