#!/bin/bash -ex

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

rm -rf ./dist ./build *.egg-info/
./setup.py sdist bdist_wheel
BATCH_PACKAGE=$(./setup.py --fullname | tr -d "\n")

docker build "$@" -f docker/Dockerfile . --build-arg BATCH_PACKAGE=${BATCH_PACKAGE} -t batch-processing-kit:test
