#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# So that we can run the tests with any cwd.
ROOT_DIR="`dirname \"$0\"`"
ROOT_DIR="`( cd \"$MY_PATH\" && pwd )`"
pushd $ROOT_DIR || exit

python -m unittest discover -v tests -t "${ROOT_DIR}"

popd