#!/usr/bin/env python3

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

import sys
import os

from examples.speech_sdk.batch_config import SpeechSDKBatchConfig

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))
from batchkit import client
from examples.speech_sdk.parser import parse_cmdline


# Main entry point
if __name__ == '__main__':
    args = parse_cmdline()
    client.run(args, SpeechSDKBatchConfig)
    exit(0)
