# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AudioConfig.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AudioConfig.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x41udioConfig.proto\x12\x18skyman.languageId.rpc.v1\"\xad\x03\n\x0b\x41udioConfig\x12\x44\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32\x32.skyman.languageId.rpc.v1.AudioConfig.EncodingType\x12\x45\n\x0bsample_rate\x18\x02 \x01(\x0e\x32\x30.skyman.languageId.rpc.v1.AudioConfig.SampleRate\x12\x45\n\x0bsample_type\x18\x03 \x01(\x0e\x32\x30.skyman.languageId.rpc.v1.AudioConfig.SampleType\x12@\n\x08\x63hannels\x18\x04 \x01(\x0e\x32..skyman.languageId.rpc.v1.AudioConfig.Channels\"!\n\x0c\x45ncodingType\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03PCM\x10\x01\"/\n\nSampleRate\x12\x10\n\x0cSAMPLE_16KHZ\x10\x00\x12\x0f\n\x0bSAMPLE_8KHZ\x10\x01\"\x1e\n\nSampleType\x12\x10\n\x0cSAMPLE_S16LE\x10\x00\"\x14\n\x08\x43hannels\x12\x08\n\x04MONO\x10\x00\x62\x06proto3'
)



_AUDIOCONFIG_ENCODINGTYPE = _descriptor.EnumDescriptor(
  name='EncodingType',
  full_name='skyman.languageId.rpc.v1.AudioConfig.EncodingType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PCM', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=341,
  serialized_end=374,
)
_sym_db.RegisterEnumDescriptor(_AUDIOCONFIG_ENCODINGTYPE)

_AUDIOCONFIG_SAMPLERATE = _descriptor.EnumDescriptor(
  name='SampleRate',
  full_name='skyman.languageId.rpc.v1.AudioConfig.SampleRate',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SAMPLE_16KHZ', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAMPLE_8KHZ', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=376,
  serialized_end=423,
)
_sym_db.RegisterEnumDescriptor(_AUDIOCONFIG_SAMPLERATE)

_AUDIOCONFIG_SAMPLETYPE = _descriptor.EnumDescriptor(
  name='SampleType',
  full_name='skyman.languageId.rpc.v1.AudioConfig.SampleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SAMPLE_S16LE', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=425,
  serialized_end=455,
)
_sym_db.RegisterEnumDescriptor(_AUDIOCONFIG_SAMPLETYPE)

_AUDIOCONFIG_CHANNELS = _descriptor.EnumDescriptor(
  name='Channels',
  full_name='skyman.languageId.rpc.v1.AudioConfig.Channels',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MONO', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=457,
  serialized_end=477,
)
_sym_db.RegisterEnumDescriptor(_AUDIOCONFIG_CHANNELS)


_AUDIOCONFIG = _descriptor.Descriptor(
  name='AudioConfig',
  full_name='skyman.languageId.rpc.v1.AudioConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encoding', full_name='skyman.languageId.rpc.v1.AudioConfig.encoding', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='skyman.languageId.rpc.v1.AudioConfig.sample_rate', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_type', full_name='skyman.languageId.rpc.v1.AudioConfig.sample_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='skyman.languageId.rpc.v1.AudioConfig.channels', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AUDIOCONFIG_ENCODINGTYPE,
    _AUDIOCONFIG_SAMPLERATE,
    _AUDIOCONFIG_SAMPLETYPE,
    _AUDIOCONFIG_CHANNELS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=477,
)

_AUDIOCONFIG.fields_by_name['encoding'].enum_type = _AUDIOCONFIG_ENCODINGTYPE
_AUDIOCONFIG.fields_by_name['sample_rate'].enum_type = _AUDIOCONFIG_SAMPLERATE
_AUDIOCONFIG.fields_by_name['sample_type'].enum_type = _AUDIOCONFIG_SAMPLETYPE
_AUDIOCONFIG.fields_by_name['channels'].enum_type = _AUDIOCONFIG_CHANNELS
_AUDIOCONFIG_ENCODINGTYPE.containing_type = _AUDIOCONFIG
_AUDIOCONFIG_SAMPLERATE.containing_type = _AUDIOCONFIG
_AUDIOCONFIG_SAMPLETYPE.containing_type = _AUDIOCONFIG
_AUDIOCONFIG_CHANNELS.containing_type = _AUDIOCONFIG
DESCRIPTOR.message_types_by_name['AudioConfig'] = _AUDIOCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioConfig = _reflection.GeneratedProtocolMessageType('AudioConfig', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOCONFIG,
  '__module__' : 'AudioConfig_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.AudioConfig)
  })
_sym_db.RegisterMessage(AudioConfig)


# @@protoc_insertion_point(module_scope)
