# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FinalResultMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FinalResultMessage.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18\x46inalResultMessage.proto\x12\x18skyman.languageId.rpc.v1\"\xa5\x04\n\x12\x46inalResultMessage\x12\x19\n\x11\x61udio_duration_ms\x18\x01 \x01(\r\x12\x1a\n\x12speech_duration_ms\x18\x02 \x01(\r\x12\x10\n\x08language\x18\x03 \x01(\t\x12K\n\nconfidence\x18\x04 \x01(\x0e\x32\x37.skyman.languageId.rpc.v1.FinalResultMessage.Confidence\x12H\n\x06scores\x18\x05 \x03(\x0b\x32\x38.skyman.languageId.rpc.v1.FinalResultMessage.ScoresEntry\x12\x0e\n\x06locale\x18\x06 \x01(\t\x12\x1d\n\x15normalized_confidence\x18\x07 \x01(\x02\x12\x17\n\x0fstart_offset_ms\x18\x08 \x01(\r\x12\x15\n\rend_offset_ms\x18\t \x01(\r\x12\x43\n\x06status\x18\n \x01(\x0e\x32\x33.skyman.languageId.rpc.v1.FinalResultMessage.Status\x1a-\n\x0bScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"8\n\nConfidence\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04HIGH\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x07\n\x03LOW\x10\x03\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07SILENCE\x10\x01\x62\x06proto3'
)



_FINALRESULTMESSAGE_CONFIDENCE = _descriptor.EnumDescriptor(
  name='Confidence',
  full_name='skyman.languageId.rpc.v1.FinalResultMessage.Confidence',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=512,
  serialized_end=568,
)
_sym_db.RegisterEnumDescriptor(_FINALRESULTMESSAGE_CONFIDENCE)

_FINALRESULTMESSAGE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='skyman.languageId.rpc.v1.FinalResultMessage.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SILENCE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=570,
  serialized_end=604,
)
_sym_db.RegisterEnumDescriptor(_FINALRESULTMESSAGE_STATUS)


_FINALRESULTMESSAGE_SCORESENTRY = _descriptor.Descriptor(
  name='ScoresEntry',
  full_name='skyman.languageId.rpc.v1.FinalResultMessage.ScoresEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='skyman.languageId.rpc.v1.FinalResultMessage.ScoresEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='skyman.languageId.rpc.v1.FinalResultMessage.ScoresEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=510,
)

_FINALRESULTMESSAGE = _descriptor.Descriptor(
  name='FinalResultMessage',
  full_name='skyman.languageId.rpc.v1.FinalResultMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_duration_ms', full_name='skyman.languageId.rpc.v1.FinalResultMessage.audio_duration_ms', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speech_duration_ms', full_name='skyman.languageId.rpc.v1.FinalResultMessage.speech_duration_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='skyman.languageId.rpc.v1.FinalResultMessage.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='skyman.languageId.rpc.v1.FinalResultMessage.confidence', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scores', full_name='skyman.languageId.rpc.v1.FinalResultMessage.scores', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locale', full_name='skyman.languageId.rpc.v1.FinalResultMessage.locale', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalized_confidence', full_name='skyman.languageId.rpc.v1.FinalResultMessage.normalized_confidence', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_offset_ms', full_name='skyman.languageId.rpc.v1.FinalResultMessage.start_offset_ms', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_offset_ms', full_name='skyman.languageId.rpc.v1.FinalResultMessage.end_offset_ms', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='skyman.languageId.rpc.v1.FinalResultMessage.status', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FINALRESULTMESSAGE_SCORESENTRY, ],
  enum_types=[
    _FINALRESULTMESSAGE_CONFIDENCE,
    _FINALRESULTMESSAGE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=604,
)

_FINALRESULTMESSAGE_SCORESENTRY.containing_type = _FINALRESULTMESSAGE
_FINALRESULTMESSAGE.fields_by_name['confidence'].enum_type = _FINALRESULTMESSAGE_CONFIDENCE
_FINALRESULTMESSAGE.fields_by_name['scores'].message_type = _FINALRESULTMESSAGE_SCORESENTRY
_FINALRESULTMESSAGE.fields_by_name['status'].enum_type = _FINALRESULTMESSAGE_STATUS
_FINALRESULTMESSAGE_CONFIDENCE.containing_type = _FINALRESULTMESSAGE
_FINALRESULTMESSAGE_STATUS.containing_type = _FINALRESULTMESSAGE
DESCRIPTOR.message_types_by_name['FinalResultMessage'] = _FINALRESULTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FinalResultMessage = _reflection.GeneratedProtocolMessageType('FinalResultMessage', (_message.Message,), {

  'ScoresEntry' : _reflection.GeneratedProtocolMessageType('ScoresEntry', (_message.Message,), {
    'DESCRIPTOR' : _FINALRESULTMESSAGE_SCORESENTRY,
    '__module__' : 'FinalResultMessage_pb2'
    # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.FinalResultMessage.ScoresEntry)
    })
  ,
  'DESCRIPTOR' : _FINALRESULTMESSAGE,
  '__module__' : 'FinalResultMessage_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.FinalResultMessage)
  })
_sym_db.RegisterMessage(FinalResultMessage)
_sym_db.RegisterMessage(FinalResultMessage.ScoresEntry)


_FINALRESULTMESSAGE_SCORESENTRY._options = None
# @@protoc_insertion_point(module_scope)
