# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IdentificationCompletedMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IdentificationCompletedMessage.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n$IdentificationCompletedMessage.proto\x12\x18skyman.languageId.rpc.v1\"\x9a\x02\n\x1eIdentificationCompletedMessage\x12V\n\nend_reason\x18\x01 \x01(\x0e\x32\x42.skyman.languageId.rpc.v1.IdentificationCompletedMessage.EndReason\x12\x17\n\x0fstart_offset_ms\x18\x02 \x01(\r\x12\x15\n\rend_offset_ms\x18\x03 \x01(\r\x12\x19\n\x11\x61udio_duration_ms\x18\x04 \x01(\r\"U\n\tEndReason\x12\x18\n\x14INITALSILENCETIMEOUT\x10\x00\x12\x15\n\x11\x45NDSILENCETIMEOUT\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x0c\n\x08\x41UDIOEND\x10\x03\x62\x06proto3'
)



_IDENTIFICATIONCOMPLETEDMESSAGE_ENDREASON = _descriptor.EnumDescriptor(
  name='EndReason',
  full_name='skyman.languageId.rpc.v1.IdentificationCompletedMessage.EndReason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INITALSILENCETIMEOUT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENDSILENCETIMEOUT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUDIOEND', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=264,
  serialized_end=349,
)
_sym_db.RegisterEnumDescriptor(_IDENTIFICATIONCOMPLETEDMESSAGE_ENDREASON)


_IDENTIFICATIONCOMPLETEDMESSAGE = _descriptor.Descriptor(
  name='IdentificationCompletedMessage',
  full_name='skyman.languageId.rpc.v1.IdentificationCompletedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='end_reason', full_name='skyman.languageId.rpc.v1.IdentificationCompletedMessage.end_reason', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_offset_ms', full_name='skyman.languageId.rpc.v1.IdentificationCompletedMessage.start_offset_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_offset_ms', full_name='skyman.languageId.rpc.v1.IdentificationCompletedMessage.end_offset_ms', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_duration_ms', full_name='skyman.languageId.rpc.v1.IdentificationCompletedMessage.audio_duration_ms', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IDENTIFICATIONCOMPLETEDMESSAGE_ENDREASON,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=349,
)

_IDENTIFICATIONCOMPLETEDMESSAGE.fields_by_name['end_reason'].enum_type = _IDENTIFICATIONCOMPLETEDMESSAGE_ENDREASON
_IDENTIFICATIONCOMPLETEDMESSAGE_ENDREASON.containing_type = _IDENTIFICATIONCOMPLETEDMESSAGE
DESCRIPTOR.message_types_by_name['IdentificationCompletedMessage'] = _IDENTIFICATIONCOMPLETEDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdentificationCompletedMessage = _reflection.GeneratedProtocolMessageType('IdentificationCompletedMessage', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFICATIONCOMPLETEDMESSAGE,
  '__module__' : 'IdentificationCompletedMessage_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.IdentificationCompletedMessage)
  })
_sym_db.RegisterMessage(IdentificationCompletedMessage)


# @@protoc_insertion_point(module_scope)
