# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IdentifierConfig.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentifierSegmentationConfig_pb2 as IdentifierSegmentationConfig__pb2
import IdentifierTimeoutConfig_pb2 as IdentifierTimeoutConfig__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IdentifierConfig.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16IdentifierConfig.proto\x12\x18skyman.languageId.rpc.v1\x1a\"IdentifierSegmentationConfig.proto\x1a\x1dIdentifierTimeoutConfig.proto\"\xd6\x04\n\x10IdentifierConfig\x12\x11\n\tlanguages\x18\x01 \x03(\t\x12#\n\x1bresponse_speech_interval_ms\x18\x02 \x01(\r\x12J\n\x08metadata\x18\x03 \x03(\x0b\x32\x38.skyman.languageId.rpc.v1.IdentifierConfig.MetadataEntry\x12\"\n\x16maximun_audio_duration\x18\x04 \x01(\x01\x42\x02\x18\x01\x12\x0f\n\x07locales\x18\x05 \x03(\t\x12\x1a\n\x12max_audio_duration\x18\x06 \x01(\x01\x12\x1b\n\x13max_speech_duration\x18\x07 \x01(\x01\x12,\n\x04mode\x18\x08 \x01(\x0e\x32\x1e.skyman.languageId.rpc.v1.Mode\x12\x34\n\x08priority\x18\t \x01(\x0e\x32\".skyman.languageId.rpc.v1.Priority\x12\x17\n\x0f\x64ominant_locale\x18\n \x01(\t\x12U\n\x15segmentation_settings\x18\x0b \x01(\x0b\x32\x36.skyman.languageId.rpc.v1.IdentifierSegmentationConfig\x12K\n\x10timeout_settings\x18\x0c \x01(\x0b\x32\x31.skyman.languageId.rpc.v1.IdentifierTimeoutConfig\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*5\n\x04Mode\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0e\n\nCONTINUOUS\x10\x01\x12\x10\n\x0cSEGMENTATION\x10\x02*P\n\x08Priority\x12\x15\n\x11PRIORITIZEDEFAULT\x10\x00\x12\x16\n\x12PRIORITIZEACCURACY\x10\x01\x12\x15\n\x11PRIORITIZELATENCY\x10\x02\x62\x06proto3'
  ,
  dependencies=[IdentifierSegmentationConfig__pb2.DESCRIPTOR,IdentifierTimeoutConfig__pb2.DESCRIPTOR,])

_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='skyman.languageId.rpc.v1.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTINUOUS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEGMENTATION', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=720,
  serialized_end=773,
)
_sym_db.RegisterEnumDescriptor(_MODE)

Mode = enum_type_wrapper.EnumTypeWrapper(_MODE)
_PRIORITY = _descriptor.EnumDescriptor(
  name='Priority',
  full_name='skyman.languageId.rpc.v1.Priority',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIORITIZEDEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIORITIZEACCURACY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIORITIZELATENCY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=775,
  serialized_end=855,
)
_sym_db.RegisterEnumDescriptor(_PRIORITY)

Priority = enum_type_wrapper.EnumTypeWrapper(_PRIORITY)
DEFAULT = 0
CONTINUOUS = 1
SEGMENTATION = 2
PRIORITIZEDEFAULT = 0
PRIORITIZEACCURACY = 1
PRIORITIZELATENCY = 2



_IDENTIFIERCONFIG_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='skyman.languageId.rpc.v1.IdentifierConfig.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='skyman.languageId.rpc.v1.IdentifierConfig.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='skyman.languageId.rpc.v1.IdentifierConfig.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=671,
  serialized_end=718,
)

_IDENTIFIERCONFIG = _descriptor.Descriptor(
  name='IdentifierConfig',
  full_name='skyman.languageId.rpc.v1.IdentifierConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='languages', full_name='skyman.languageId.rpc.v1.IdentifierConfig.languages', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_speech_interval_ms', full_name='skyman.languageId.rpc.v1.IdentifierConfig.response_speech_interval_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='skyman.languageId.rpc.v1.IdentifierConfig.metadata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maximun_audio_duration', full_name='skyman.languageId.rpc.v1.IdentifierConfig.maximun_audio_duration', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\030\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locales', full_name='skyman.languageId.rpc.v1.IdentifierConfig.locales', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_audio_duration', full_name='skyman.languageId.rpc.v1.IdentifierConfig.max_audio_duration', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_speech_duration', full_name='skyman.languageId.rpc.v1.IdentifierConfig.max_speech_duration', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='skyman.languageId.rpc.v1.IdentifierConfig.mode', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='skyman.languageId.rpc.v1.IdentifierConfig.priority', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dominant_locale', full_name='skyman.languageId.rpc.v1.IdentifierConfig.dominant_locale', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segmentation_settings', full_name='skyman.languageId.rpc.v1.IdentifierConfig.segmentation_settings', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout_settings', full_name='skyman.languageId.rpc.v1.IdentifierConfig.timeout_settings', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_IDENTIFIERCONFIG_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=718,
)

_IDENTIFIERCONFIG_METADATAENTRY.containing_type = _IDENTIFIERCONFIG
_IDENTIFIERCONFIG.fields_by_name['metadata'].message_type = _IDENTIFIERCONFIG_METADATAENTRY
_IDENTIFIERCONFIG.fields_by_name['mode'].enum_type = _MODE
_IDENTIFIERCONFIG.fields_by_name['priority'].enum_type = _PRIORITY
_IDENTIFIERCONFIG.fields_by_name['segmentation_settings'].message_type = IdentifierSegmentationConfig__pb2._IDENTIFIERSEGMENTATIONCONFIG
_IDENTIFIERCONFIG.fields_by_name['timeout_settings'].message_type = IdentifierTimeoutConfig__pb2._IDENTIFIERTIMEOUTCONFIG
DESCRIPTOR.message_types_by_name['IdentifierConfig'] = _IDENTIFIERCONFIG
DESCRIPTOR.enum_types_by_name['Mode'] = _MODE
DESCRIPTOR.enum_types_by_name['Priority'] = _PRIORITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdentifierConfig = _reflection.GeneratedProtocolMessageType('IdentifierConfig', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _IDENTIFIERCONFIG_METADATAENTRY,
    '__module__' : 'IdentifierConfig_pb2'
    # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.IdentifierConfig.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _IDENTIFIERCONFIG,
  '__module__' : 'IdentifierConfig_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.IdentifierConfig)
  })
_sym_db.RegisterMessage(IdentifierConfig)
_sym_db.RegisterMessage(IdentifierConfig.MetadataEntry)


_IDENTIFIERCONFIG_METADATAENTRY._options = None
_IDENTIFIERCONFIG.fields_by_name['maximun_audio_duration']._options = None
# @@protoc_insertion_point(module_scope)
