# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IntermediateResultMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IntermediateResultMessage.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1fIntermediateResultMessage.proto\x12\x18skyman.languageId.rpc.v1\"\x9f\x02\n\x19IntermediateResultMessage\x12\x17\n\x0f\x61udio_offset_ms\x18\x01 \x01(\r\x12\x1a\n\x12speech_duration_ms\x18\x02 \x01(\r\x12\x10\n\x08language\x18\x03 \x01(\t\x12R\n\nconfidence\x18\x04 \x01(\x0e\x32>.skyman.languageId.rpc.v1.IntermediateResultMessage.Confidence\x12\x0e\n\x06locale\x18\x05 \x01(\t\x12\x1d\n\x15normalized_confidence\x18\x06 \x01(\x02\"8\n\nConfidence\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04HIGH\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x07\n\x03LOW\x10\x03\x62\x06proto3'
)



_INTERMEDIATERESULTMESSAGE_CONFIDENCE = _descriptor.EnumDescriptor(
  name='Confidence',
  full_name='skyman.languageId.rpc.v1.IntermediateResultMessage.Confidence',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=293,
  serialized_end=349,
)
_sym_db.RegisterEnumDescriptor(_INTERMEDIATERESULTMESSAGE_CONFIDENCE)


_INTERMEDIATERESULTMESSAGE = _descriptor.Descriptor(
  name='IntermediateResultMessage',
  full_name='skyman.languageId.rpc.v1.IntermediateResultMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_offset_ms', full_name='skyman.languageId.rpc.v1.IntermediateResultMessage.audio_offset_ms', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speech_duration_ms', full_name='skyman.languageId.rpc.v1.IntermediateResultMessage.speech_duration_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='skyman.languageId.rpc.v1.IntermediateResultMessage.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='skyman.languageId.rpc.v1.IntermediateResultMessage.confidence', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locale', full_name='skyman.languageId.rpc.v1.IntermediateResultMessage.locale', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalized_confidence', full_name='skyman.languageId.rpc.v1.IntermediateResultMessage.normalized_confidence', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INTERMEDIATERESULTMESSAGE_CONFIDENCE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=349,
)

_INTERMEDIATERESULTMESSAGE.fields_by_name['confidence'].enum_type = _INTERMEDIATERESULTMESSAGE_CONFIDENCE
_INTERMEDIATERESULTMESSAGE_CONFIDENCE.containing_type = _INTERMEDIATERESULTMESSAGE
DESCRIPTOR.message_types_by_name['IntermediateResultMessage'] = _INTERMEDIATERESULTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntermediateResultMessage = _reflection.GeneratedProtocolMessageType('IntermediateResultMessage', (_message.Message,), {
  'DESCRIPTOR' : _INTERMEDIATERESULTMESSAGE,
  '__module__' : 'IntermediateResultMessage_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.IntermediateResultMessage)
  })
_sym_db.RegisterMessage(IntermediateResultMessage)


# @@protoc_insertion_point(module_scope)
