# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LanguageIdRpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SupportedLanguagesMessage_pb2 as SupportedLanguagesMessage__pb2
import EmptyMessage_pb2 as EmptyMessage__pb2
import LIDRequestMessage_pb2 as LIDRequestMessage__pb2
import LIDResponseMessage_pb2 as LIDResponseMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LanguageIdRpc.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13LanguageIdRpc.proto\x12\x18skyman.languageId.rpc.v1\x1a\x1fSupportedLanguagesMessage.proto\x1a\x12\x45mptyMessage.proto\x1a\x17LIDRequestMessage.proto\x1a\x18LIDResponseMessage.proto2\xee\x01\n\nLanguageId\x12s\n\x12SupportedLanguages\x12&.skyman.languageId.rpc.v1.EmptyMessage\x1a\x33.skyman.languageId.rpc.v1.SupportedLanguagesMessage\"\x00\x12k\n\x08Identify\x12+.skyman.languageId.rpc.v1.LIDRequestMessage\x1a,.skyman.languageId.rpc.v1.LIDResponseMessage\"\x00(\x01\x30\x01\x62\x06proto3'
  ,
  dependencies=[SupportedLanguagesMessage__pb2.DESCRIPTOR,EmptyMessage__pb2.DESCRIPTOR,LIDRequestMessage__pb2.DESCRIPTOR,LIDResponseMessage__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_LANGUAGEID = _descriptor.ServiceDescriptor(
  name='LanguageId',
  full_name='skyman.languageId.rpc.v1.LanguageId',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=154,
  serialized_end=392,
  methods=[
  _descriptor.MethodDescriptor(
    name='SupportedLanguages',
    full_name='skyman.languageId.rpc.v1.LanguageId.SupportedLanguages',
    index=0,
    containing_service=None,
    input_type=EmptyMessage__pb2._EMPTYMESSAGE,
    output_type=SupportedLanguagesMessage__pb2._SUPPORTEDLANGUAGESMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Identify',
    full_name='skyman.languageId.rpc.v1.LanguageId.Identify',
    index=1,
    containing_service=None,
    input_type=LIDRequestMessage__pb2._LIDREQUESTMESSAGE,
    output_type=LIDResponseMessage__pb2._LIDRESPONSEMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LANGUAGEID)

DESCRIPTOR.services_by_name['LanguageId'] = _LANGUAGEID

# @@protoc_insertion_point(module_scope)
