# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LIDConfigMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentifierConfig_pb2 as IdentifierConfig__pb2
import AudioConfig_pb2 as AudioConfig__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LIDConfigMessage.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16LIDConfigMessage.proto\x12\x18skyman.languageId.rpc.v1\x1a\x16IdentifierConfig.proto\x1a\x11\x41udioConfig.proto\"\x96\x01\n\x10LIDConfigMessage\x12\x45\n\x11identifier_config\x18\x01 \x01(\x0b\x32*.skyman.languageId.rpc.v1.IdentifierConfig\x12;\n\x0c\x61udio_config\x18\x02 \x01(\x0b\x32%.skyman.languageId.rpc.v1.AudioConfigb\x06proto3'
  ,
  dependencies=[IdentifierConfig__pb2.DESCRIPTOR,AudioConfig__pb2.DESCRIPTOR,])




_LIDCONFIGMESSAGE = _descriptor.Descriptor(
  name='LIDConfigMessage',
  full_name='skyman.languageId.rpc.v1.LIDConfigMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier_config', full_name='skyman.languageId.rpc.v1.LIDConfigMessage.identifier_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_config', full_name='skyman.languageId.rpc.v1.LIDConfigMessage.audio_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=246,
)

_LIDCONFIGMESSAGE.fields_by_name['identifier_config'].message_type = IdentifierConfig__pb2._IDENTIFIERCONFIG
_LIDCONFIGMESSAGE.fields_by_name['audio_config'].message_type = AudioConfig__pb2._AUDIOCONFIG
DESCRIPTOR.message_types_by_name['LIDConfigMessage'] = _LIDCONFIGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LIDConfigMessage = _reflection.GeneratedProtocolMessageType('LIDConfigMessage', (_message.Message,), {
  'DESCRIPTOR' : _LIDCONFIGMESSAGE,
  '__module__' : 'LIDConfigMessage_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.LIDConfigMessage)
  })
_sym_db.RegisterMessage(LIDConfigMessage)


# @@protoc_insertion_point(module_scope)
