# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LIDRequestMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LIDConfigMessage_pb2 as LIDConfigMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LIDRequestMessage.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17LIDRequestMessage.proto\x12\x18skyman.languageId.rpc.v1\x1a\x16LIDConfigMessage.proto\"u\n\x11LIDRequestMessage\x12<\n\x06\x63onfig\x18\x01 \x01(\x0b\x32*.skyman.languageId.rpc.v1.LIDConfigMessageH\x00\x12\x17\n\raudio_payload\x18\x02 \x01(\x0cH\x00\x42\t\n\x07requestb\x06proto3'
  ,
  dependencies=[LIDConfigMessage__pb2.DESCRIPTOR,])




_LIDREQUESTMESSAGE = _descriptor.Descriptor(
  name='LIDRequestMessage',
  full_name='skyman.languageId.rpc.v1.LIDRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='skyman.languageId.rpc.v1.LIDRequestMessage.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_payload', full_name='skyman.languageId.rpc.v1.LIDRequestMessage.audio_payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='skyman.languageId.rpc.v1.LIDRequestMessage.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=77,
  serialized_end=194,
)

_LIDREQUESTMESSAGE.fields_by_name['config'].message_type = LIDConfigMessage__pb2._LIDCONFIGMESSAGE
_LIDREQUESTMESSAGE.oneofs_by_name['request'].fields.append(
  _LIDREQUESTMESSAGE.fields_by_name['config'])
_LIDREQUESTMESSAGE.fields_by_name['config'].containing_oneof = _LIDREQUESTMESSAGE.oneofs_by_name['request']
_LIDREQUESTMESSAGE.oneofs_by_name['request'].fields.append(
  _LIDREQUESTMESSAGE.fields_by_name['audio_payload'])
_LIDREQUESTMESSAGE.fields_by_name['audio_payload'].containing_oneof = _LIDREQUESTMESSAGE.oneofs_by_name['request']
DESCRIPTOR.message_types_by_name['LIDRequestMessage'] = _LIDREQUESTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LIDRequestMessage = _reflection.GeneratedProtocolMessageType('LIDRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _LIDREQUESTMESSAGE,
  '__module__' : 'LIDRequestMessage_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.LIDRequestMessage)
  })
_sym_db.RegisterMessage(LIDRequestMessage)


# @@protoc_insertion_point(module_scope)
