# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LIDResponseMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FinalResultMessage_pb2 as FinalResultMessage__pb2
import IntermediateResultMessage_pb2 as IntermediateResultMessage__pb2
import IdentificationCompletedMessage_pb2 as IdentificationCompletedMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LIDResponseMessage.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18LIDResponseMessage.proto\x12\x18skyman.languageId.rpc.v1\x1a\x18\x46inalResultMessage.proto\x1a\x1fIntermediateResultMessage.proto\x1a$IdentificationCompletedMessage.proto\"\x97\x02\n\x12LIDResponseMessage\x12\x44\n\x0c\x66inal_result\x18\x01 \x01(\x0b\x32,.skyman.languageId.rpc.v1.FinalResultMessageH\x00\x12R\n\x13intermediate_result\x18\x02 \x01(\x0b\x32\x33.skyman.languageId.rpc.v1.IntermediateResultMessageH\x00\x12\\\n\x18identification_completed\x18\x03 \x01(\x0b\x32\x38.skyman.languageId.rpc.v1.IdentificationCompletedMessageH\x00\x42\t\n\x07messageb\x06proto3'
  ,
  dependencies=[FinalResultMessage__pb2.DESCRIPTOR,IntermediateResultMessage__pb2.DESCRIPTOR,IdentificationCompletedMessage__pb2.DESCRIPTOR,])




_LIDRESPONSEMESSAGE = _descriptor.Descriptor(
  name='LIDResponseMessage',
  full_name='skyman.languageId.rpc.v1.LIDResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='final_result', full_name='skyman.languageId.rpc.v1.LIDResponseMessage.final_result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intermediate_result', full_name='skyman.languageId.rpc.v1.LIDResponseMessage.intermediate_result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identification_completed', full_name='skyman.languageId.rpc.v1.LIDResponseMessage.identification_completed', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='skyman.languageId.rpc.v1.LIDResponseMessage.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=152,
  serialized_end=431,
)

_LIDRESPONSEMESSAGE.fields_by_name['final_result'].message_type = FinalResultMessage__pb2._FINALRESULTMESSAGE
_LIDRESPONSEMESSAGE.fields_by_name['intermediate_result'].message_type = IntermediateResultMessage__pb2._INTERMEDIATERESULTMESSAGE
_LIDRESPONSEMESSAGE.fields_by_name['identification_completed'].message_type = IdentificationCompletedMessage__pb2._IDENTIFICATIONCOMPLETEDMESSAGE
_LIDRESPONSEMESSAGE.oneofs_by_name['message'].fields.append(
  _LIDRESPONSEMESSAGE.fields_by_name['final_result'])
_LIDRESPONSEMESSAGE.fields_by_name['final_result'].containing_oneof = _LIDRESPONSEMESSAGE.oneofs_by_name['message']
_LIDRESPONSEMESSAGE.oneofs_by_name['message'].fields.append(
  _LIDRESPONSEMESSAGE.fields_by_name['intermediate_result'])
_LIDRESPONSEMESSAGE.fields_by_name['intermediate_result'].containing_oneof = _LIDRESPONSEMESSAGE.oneofs_by_name['message']
_LIDRESPONSEMESSAGE.oneofs_by_name['message'].fields.append(
  _LIDRESPONSEMESSAGE.fields_by_name['identification_completed'])
_LIDRESPONSEMESSAGE.fields_by_name['identification_completed'].containing_oneof = _LIDRESPONSEMESSAGE.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['LIDResponseMessage'] = _LIDRESPONSEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LIDResponseMessage = _reflection.GeneratedProtocolMessageType('LIDResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _LIDRESPONSEMESSAGE,
  '__module__' : 'LIDResponseMessage_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.LIDResponseMessage)
  })
_sym_db.RegisterMessage(LIDResponseMessage)


# @@protoc_insertion_point(module_scope)
