# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SegmentResultMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SegmentResultMessage.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1aSegmentResultMessage.proto\x12\x18skyman.languageId.rpc.v1\"\x88\x02\n\x14SegmentResultMessage\x12\x11\n\toffset_ms\x18\x01 \x01(\r\x12\x17\n\x0fstart_offset_ms\x18\x02 \x01(\r\x12\x1a\n\x12speech_duration_ms\x18\x03 \x01(\r\x12J\n\x06scores\x18\x04 \x03(\x0b\x32:.skyman.languageId.rpc.v1.SegmentResultMessage.ScoresEntry\x12\x0e\n\x06locale\x18\x05 \x01(\t\x12\x1d\n\x15normalized_confidence\x18\x06 \x01(\x02\x1a-\n\x0bScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3'
)




_SEGMENTRESULTMESSAGE_SCORESENTRY = _descriptor.Descriptor(
  name='ScoresEntry',
  full_name='skyman.languageId.rpc.v1.SegmentResultMessage.ScoresEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='skyman.languageId.rpc.v1.SegmentResultMessage.ScoresEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='skyman.languageId.rpc.v1.SegmentResultMessage.ScoresEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=321,
)

_SEGMENTRESULTMESSAGE = _descriptor.Descriptor(
  name='SegmentResultMessage',
  full_name='skyman.languageId.rpc.v1.SegmentResultMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset_ms', full_name='skyman.languageId.rpc.v1.SegmentResultMessage.offset_ms', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_offset_ms', full_name='skyman.languageId.rpc.v1.SegmentResultMessage.start_offset_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speech_duration_ms', full_name='skyman.languageId.rpc.v1.SegmentResultMessage.speech_duration_ms', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scores', full_name='skyman.languageId.rpc.v1.SegmentResultMessage.scores', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locale', full_name='skyman.languageId.rpc.v1.SegmentResultMessage.locale', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalized_confidence', full_name='skyman.languageId.rpc.v1.SegmentResultMessage.normalized_confidence', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SEGMENTRESULTMESSAGE_SCORESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=321,
)

_SEGMENTRESULTMESSAGE_SCORESENTRY.containing_type = _SEGMENTRESULTMESSAGE
_SEGMENTRESULTMESSAGE.fields_by_name['scores'].message_type = _SEGMENTRESULTMESSAGE_SCORESENTRY
DESCRIPTOR.message_types_by_name['SegmentResultMessage'] = _SEGMENTRESULTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SegmentResultMessage = _reflection.GeneratedProtocolMessageType('SegmentResultMessage', (_message.Message,), {

  'ScoresEntry' : _reflection.GeneratedProtocolMessageType('ScoresEntry', (_message.Message,), {
    'DESCRIPTOR' : _SEGMENTRESULTMESSAGE_SCORESENTRY,
    '__module__' : 'SegmentResultMessage_pb2'
    # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.SegmentResultMessage.ScoresEntry)
    })
  ,
  'DESCRIPTOR' : _SEGMENTRESULTMESSAGE,
  '__module__' : 'SegmentResultMessage_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.SegmentResultMessage)
  })
_sym_db.RegisterMessage(SegmentResultMessage)
_sym_db.RegisterMessage(SegmentResultMessage.ScoresEntry)


_SEGMENTRESULTMESSAGE_SCORESENTRY._options = None
# @@protoc_insertion_point(module_scope)
