# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SupportedLanguagesMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SupportedLanguagesMessage.proto',
  package='skyman.languageId.rpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1fSupportedLanguagesMessage.proto\x12\x18skyman.languageId.rpc.v1\".\n\x19SupportedLanguagesMessage\x12\x11\n\tlanguages\x18\x01 \x03(\tb\x06proto3'
)




_SUPPORTEDLANGUAGESMESSAGE = _descriptor.Descriptor(
  name='SupportedLanguagesMessage',
  full_name='skyman.languageId.rpc.v1.SupportedLanguagesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='languages', full_name='skyman.languageId.rpc.v1.SupportedLanguagesMessage.languages', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['SupportedLanguagesMessage'] = _SUPPORTEDLANGUAGESMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SupportedLanguagesMessage = _reflection.GeneratedProtocolMessageType('SupportedLanguagesMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUPPORTEDLANGUAGESMESSAGE,
  '__module__' : 'SupportedLanguagesMessage_pb2'
  # @@protoc_insertion_point(class_scope:skyman.languageId.rpc.v1.SupportedLanguagesMessage)
  })
_sym_db.RegisterMessage(SupportedLanguagesMessage)


# @@protoc_insertion_point(module_scope)
