#!/usr/bin/env python3

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

import sys
import os

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))
from batchkit.client import run
from batchkit.parser import parse_cmdline


# Main entry point
if __name__ == '__main__':
    args = parse_cmdline()
    run(args)
    exit(0)
