#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# to only publish batchkit_examples and NOT batchkit pypi package (lower priority)
    # from pipeline cmd, do git diff to determine which files were actually modified between head and head-1
    # would still have GitHub repo versions match but would ONLY publish pypi package that was actually modified as determined by git diff

# pushing to pull request, so check version against current commit to master
HASH=$(git log --pretty=format:"%H" --first-parent master | head -n 1)
BATCHKIT_OLD=$(curl -s https://raw.githubusercontent.com/microsoft/batch-processing-kit/$HASH/setup_batchkit.py | grep version= | awk '{$1=$1};1' | cut -c1-8 --complement | tr -d ,\')
BATCHKIT_NEW=$(python $setupBatchkit --version)
echo INFO: Current master \'$pypiBatchkit\' is version \'$BATCHKIT_OLD\'. Pushed \'$pypiBatchkit\' is version \'$BATCHKIT_NEW\'

if [ "$BATCHKIT_OLD" = "$BATCHKIT_NEW" ]
then 
    echo ERROR: Increment Python package version for \'$pypiBatchkit\'. Current package version is the same as package version in current commit to master
    # exit 1
fi