#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

pip install batchkit batchkit_examples_speechsdk

declare BATCHKIT_OLD=$(pip show batchkit | grep Version | cut -c10-16)
declare BATCHKIT_NEW=$(python setup_batchkit.py --version)
echo "INFO: Latest published 'batchkit' is version '$BATCHKIT_OLD'. New 'batchkit' is version '$BATCHKIT_NEW'"

declare BATCHKIT_EX_OLD=$(pip show batchkit_examples_speechsdk | grep Version | cut -c10-16)
declare BATCHKIT_EX_NEW=$(python setup_examples.py --version)
echo "INFO: Latest published 'batchkit_examples_speechsdk' is version '$BATCHKIT_EX_OLD'. New 'batchkit_examples_speechsdk' is version '$BATCHKIT_EX_NEW'"

EXIT=false
if [ "$BATCHKIT_OLD" = "$BATCHKIT_NEW" ]
then 
    echo "ERROR: Increment Python package version for 'batchkit'. Current package version is the same as published package version"
    EXIT=true
fi

if [ "$BATCHKIT_EX_OLD" = "$BATCHKIT_EX_NEW" ]
then 
    echo "ERROR: Increment Python package version for 'batchkit_examples_speechsdk'. Current package version is the same as published package version"
    EXIT=true
fi

if [ "$BATCHKIT_NEW" != "$BATCHKIT_EX_NEW" ]
then 
    echo "ERROR: Python package versions for 'batchkit' and 'batchkit_examples_speechsdk' must match"
    EXIT=true
else
    echo "INFO: Python package versions for 'batchkit' and 'batchkit_examples_speechsdk' match as expected"
fi

if [ "$EXIT" = true ]
then 
    exit 1
fi